### ISSUE TITLE
[BUG]半屏弹窗组件真机与开发者工具中所展现的样式不符.

### ISSUE THREAD

**Issue by Abbotton** [wechat-miniprogram/weui-miniprogram#158]
## Bug描述
半屏弹窗组件,小程序开发工具里面底部扩展按钮是水平排列的.
而真机调试时底部扩展按钮是垂直排列叠在一起的.
请问默认样式就是这样还是兼容性问题?

## 复现方式
真机: vivo-V2001A(vivo x50),
微信版本v8.0.1,
开发者工具: stable v1.05.2102010
扫描weui官方组件库小程序即可看到.
## 版本信息
- weui 版本 [useExtendedLib 引入则直接填写 useExtendedLib] :useExtendedLib

**Comment by Abbotton** [comment]
实测通过自定义样式可以调整为一行显示,但还是想得到官方的回复.
```css
.weui-half-screen-dialog__ft {
  display: flex !important;
}
```
