### ISSUE TITLE
[FEATURE] useExtendedLib 引入时除了使用 ext-class，以及逐个覆盖样式类之外，还有什么更好的方式来定制主题颜色（按钮、导航背景等）

### ISSUE THREAD

**Issue by jaggerwang** [wechat-miniprogram/weui-miniprogram#258]
## 遇到的问题
想修改主按钮颜色，目前只能通过下面的自定义样式类来覆盖，很难覆盖全，比如下面的就漏了 active 模式。

```css
button[type="primary"],
button[type="primary"][loading] {
  background-color: #39495c;
}
button[type="primary"][plain] {
  border-color: #39495c;
  color: #5480a3;
}
button[type="default"],
button[type="default"][loading] {
  color: #39495c;
}
```

## 特性方案
希望可以通过在 app.json 或其它文件中配置主题颜色。

**Comment by Tidyzq** [comment]
你好，你提供的代码中覆盖的其实是内置的 button 组件样式，而不是 weui 组件的样式（尽管他们两长得很像）。

weui 组件库中没有给 button 封装一个单独的 button 组件，所以建议是在使用时添加一个 class 来覆盖样式，比如：

```html
<button class="weui-btn my-btn" >123</button>
```
```css
.my-btn {
  border-color: #39495c !important;
  color: #5480a3 !important;
}
```
