### ISSUE TITLE
toptips和navigation-bar一起用的时候被遮挡

### ISSUE THREAD

**Issue by BigPiter** [wechat-miniprogram/weui-miniprogram#55]
toptips和navigation-bar一起用的时候被遮挡能否做一下这个兼容？

**Comment by edwardfhsiao** [comment]
实在没办法了，先这样搞

```css
.weui-toptips {
	top: 40px!important;
}

.weui-toptips.weui-toptips_show {
	z-index: 9999;
}
```
