### ISSUE TITLE
Searchbar点击搜索结果选项，怎么关闭搜索结果面板

### ISSUE THREAD

**Issue by MissNanLan** [wechat-miniprogram/weui-miniprogram#83]
请问下searchbar组件，怎么在点击搜索结果的时候关闭搜索结果的面板

**Comment by xysDavid** [comment]
@MissNanLan 目前暂时不支持参数配置这个交互。

有一种实现方案，然后通过外层加 class 和相关的样式，控制是否需要展示结果面板。

比如页面的 wxss 中多加一条这样的样式：

```css
.result-hidden .search-result {
    display: none;
}
```

然后就可以通过在外层新增`result-hidden`的 class 隐藏结果。

当需要展示结果面板的时候，再把`result-hidden`去掉，比如触发`focus`事件的时候，也可以根据你的需求进行控制。
